### PR TITLE
Update tonic to 0.10.0

### PR DESCRIPTION
**Pull request by rodoufu**
Fixes #

Fixes and issue when using tonic 0.10.0

## Changes

Update tonic version to 0.10.0

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by djc** [comment]
Why did you close this? Would be nice to have.

**Comment by rodoufu** [comment]
> Why did you close this? Would be nice to have.

@djc I need to fix all the build issues before opening reopening it.

**Comment by TommyCpp** [comment]
Feel free to reopen it and mark it as a draft while you are working the build fix

**Comment by djc** [comment]
Going to reopen to make sure we don't forget this. (Also note that this doesn't include -stackdriver but probably should.)

**Comment by waynexia** [comment]
Hi! Thanks for bringing this up. I'm stuck on this as one of my other dependents has to bump tonic's version to `0.10`. How could I help on getting this merged?

**Comment by getong** [comment]
Two month ago,  try again?

**Comment by rodoufu** [comment]
After merging https://github.com/open-telemetry/opentelemetry-rust/pull/1457 where the workspace dependencies are described in the workspace manifest will be easier to fix this one an update tonic.

**Comment by flokli** [comment]
@rodoufu can you rebase this? There's also https://github.com/open-telemetry/opentelemetry-rust/pull/1252 with the same goal, maybe there's some useful context there, too.

**Pull request closed without merging**
