### PR TITLE
stackdriver: update gcp_auth dependency

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
Failures seem to be unrelated.

**Comment by TommyCpp** [comment]
Mostly like the new Clippy warnings introduced in the new version. #630 should address them. I may take another look at the issue with the nightly toolchain(coverage) tomorrow.

**Comment by TommyCpp** [comment]
May need to rebase on the master branch. There is wired CLA setting prevent me from updating branch directly

**Review by TommyCpp — APPROVED** [review]

**Comment by djc** [comment]
I rebased this but was unable to push it:

```
remote: error: GH006: Protected branch update failed for refs/heads/update-gcp-auth.
remote: error: Cannot force-push to this protected branch
To github.com:open-telemetry/opentelemetry-rust.git
 ! [remote rejected] update-gcp-auth -> update-gcp-auth (protected branch hook declined)
error: failed to push some refs to 'github.com:open-telemetry/opentelemetry-rust.git'
```

**Comment by TommyCpp** [comment]
I recall there was an issue that CLA protection extended to all branches in the repo instead of just the main branch. Let me double-check in CNCF's Slack.

**Comment by TommyCpp** [comment]
I guess CNCF just enforced easyCLA to all branches and encouraged ppl to use forked repo for PRs. One possible workaround I found is someone says we may be able to create a branch protecting rule for a specific branch so that we can do a force push. Link to the slack thread: https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1630079128006700.

Not sure if you have the right to do so @jtescher. Otherwise, we may need to bring the issue to a TC member or admin.

**Comment by jtescher** [comment]
I don't have admin either, think we may need a TC member.

**Comment by TommyCpp** [comment]
@djc @jtescher 😞 Looks like we need to recreate those PRs from a forked repo. The easyCLA is a global setup.

**Comment by djc** [comment]
Okay, see #639.

**Pull request closed without merging**
