### PR TITLE
chore: cleanup pin-project dep

### PR DESCRIPTION
**Pull request by matklad**
* remove pin-project from crates which weren't actually using it
* switch to pin-project-lite to improve compilation time and impose
  fewer deps at consumers (ecosystem migrated to -lite awhile ago
  https://github.com/tokio-rs/tokio/pull/1778)

### CODE REVIEW

**Comment by matklad** [comment]
You might want to check this setting: 

image


to make sure that PRs get tested. At the moment, I am seeing this: 

image

**Comment by matklad** [comment]
hopefully fixed compilation error

**Comment by matklad** [comment]
fixed the clippy error -- seems unrelated, prob just new rust version.

**Comment by jtescher** [comment]
Looks good, just the lint remaining

**Comment by TommyCpp** [comment]
The nightly version seems to be broken now
https://github.com/rust-lang/rust/issues/99343

**Pull request merged**
