### PR TITLE
Mention opentelemetry-stackdriver as part of the ecosystem

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by TommyCpp** [comment]
I think we [thought about it](https://github.com/open-telemetry/opentelemetry-rust/pull/312#discussion_r513148967) back then but decided not to add it as it didn't seem to be in active development. But if that's not the case, :+1: for adding it.

**Comment by djc** [comment]
I've brought it up to date. If it goes silent again I'll fork it.

**Review by jtescher — CHANGES_REQUESTED** [review]
Can we add this to the README as well? (currently both this crate and repo root readmes, could consider making one a symlink)

**Comment by djc** [comment]
Done.

**Review by jtescher — APPROVED** [review]

**Pull request merged**
