### PR TITLE
test: use rstest for table testing sdk resource

### PR DESCRIPTION
**Pull request by pitoniak32**
fixes: #2384

## Changes
Described more in the aboved linked issue. But the goal here is using rstest to improve the test writing experience and allow for tests to have multiple cases in a more readable format.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]
LGTM!

**Comment by cijothomas** [comment]
@open-telemetry/rust-approvers Please share your thoughts. We try to avoid any external dependency in the shipped code, but for tests/infra, this is acceptable.

**Review by TommyCpp — APPROVED** [review]
I always favor table driven test methods so 👍 on this change

**Review by lalitb — APPROVED** [review]
much cleaner. I anticipate it would be more helpful for metrics tests.

**Pull request merged**
