### PR TITLE
Fix order of high and low parts of the trace_id in jaeger links

### PR DESCRIPTION
**Pull request by bodymindarts**
Fix order of arguments to [`SpanRef::new`](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-jaeger/src/thrift/jaeger.rs#L337) in opentelemetry-jaeger crate.

### CODE REVIEW

**Comment by jtescher** [comment]
Just have to sign the CLA 👍

**Comment by bodymindarts** [comment]
For stupid reasons I'm locked out of my linuxfoundation account and cannot associate this GitHub account with a new one. Is there another way?
I agree to the CLA! Just I have no idea when I'll be able to sign it because of the situation.

**Comment by jtescher** [comment]
Hm I can see if there is another way to approve it, at worst this change can be done in another PR if you don't require attribution in git.

**Comment by bodymindarts** [comment]
Cool... I would like attribution if its possible. Give me a few days to see if I can find a solution or else someone else can commit the fix if there is no other way.

**Comment by bodymindarts** [comment]
Okay I regained access and was able to sign the CLA. Don't know why it says its still required. I signed as an individual.

**Comment by jtescher** [comment]
Great it picked that up, just waiting on https://github.com/open-telemetry/opentelemetry-rust/pull/120 to have the nightly checks not block merging.

**Pull request merged**
