### PR TITLE
Ureq

### PR DESCRIPTION
**Pull request by LukeMathWalker**

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
I signed it.

**Comment by LukeMathWalker** [comment]
I signed it

**Comment by LukeMathWalker** [comment]
The CI jobs on nightly are currently broken because rustfmt is not available, but the PR is ready to be looked at @jtescher

**Comment by jtescher** [comment]
Just need someone with administrative privileges to approve https://github.com/open-telemetry/opentelemetry-rust/pull/120 or for the nightly rustfmt to start working again.

**Pull request merged**
