### PR TITLE
export MetricsExporterBuilder

### PR DESCRIPTION
**Pull request by bestgopher**

### CODE REVIEW

**Review by TommyCpp — COMMENTED** [review]
Good catch. I think this PR just need to `cargo fmt`

**Comment by bestgopher** [comment]
> Good catch. I think this PR just need to `cargo fmt`

Done!

**Review by jtescher — APPROVED** [review]

**Comment by bestgopher** [comment]
@jtescher @TommyCpp Could you update a new version to crates.io?

**Comment by TommyCpp** [comment]
https://github.com/open-telemetry/opentelemetry-rust/issues/934 I will publish one soon. There are some memory issues we want to tackle

**Comment by bestgopher** [comment]
> #934 I will publish one soon. There are some memory issues we want to tackle

OK！

**Pull request merged**
