### PR TITLE
Move myself to emeritus

### PR DESCRIPTION
**Pull request by djc**
I've unset my watch bits on this repository and would like to be moved to Emeritus status. The repository has been generating a lot of notifications for me, the majority of which for things I don't care much about. For now, there seem to be enough maintainers/approvers. Feel free to ping me explicitly for Stackdriver stuff or other things where you'd like my feedback.

### CODE REVIEW

**Review by shaun-cox — APPROVED** [review]
Thank you for all your support and stewardship!

**Review by jtescher — APPROVED** [review]
Greatly appreciate all the time and work you put in 🙏

**Comment by cijothomas** [comment]
@djc Thanks a lot for your contributions including review feedbacks! 

Is there a preferred way to reach out to you for consulting? Just tagging in PR/issue is enough?

**Comment by djc** [comment]
Yeah, I'm usually on top of my GitHub notifications.

**Comment by hdost** [comment]
Thank you @djc for your work!

**Pull request merged**
