### PR TITLE
Upgrade to Semantic Convention v1.25.0

### PR DESCRIPTION
**Pull request by lalitb**
## Changes

**Changes in v1.25.0:**

- [Service attributes have been relocated to the `registry`](https://github.com/open-telemetry/semantic-conventions/pull/758)
- Attributes like `service.name`, previously defined under `resources`, are now categorized under `attribute_groups` in the `registry`. 
- The resource model now includes a reference to `service.name` as defined within the `registry`.
 
So, the code generator in [generate-consts-from-spec.sh](https://github.com/open-telemetry/opentelemetry-rust/compare/main...lalitb:semconv-upgrade-1.25.0?expand=1#diff-27fd745c80cd6c507125d72f4f4cf028af7b6b79dc903bb1014e43c9afbcde92) is now invoked for both `resource` and `attribute_group`.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
FYI: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5539 This was removed by OTel .NET and being resurrected in contrib repo.

I think we may also move this to contrib in the future.

**Comment by lalitb** [comment]
doc generation is failing, looking into this.

```
 Documenting opentelemetry-semantic-conventions v0.14.0 (/home/runner/work/opentelemetry-rust/opentelemetry-rust/opentelemetry-semantic-conventions)
error: unresolved link to `2`
   --> opentelemetry-semantic-conventions/src/trace.rs:660:96
    |
660 | /// All the command arguments (including the command/executable itself) run by the container. [2].
    |                                                                                                ^ no item named `2` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
    = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

error: unresolved link to `2`
   --> opentelemetry-semantic-conventions/src/trace.rs:667:94
    |
667 | /// The full command run by the container as a single string representing the full command. [2].
    |                                                                                              ^ no item named `2` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: could not document `opentelemetry-semantic-conventions`
```

**Comment by lalitb** [comment]
> I think we may also move this to contrib in the future.

Yes good to discuss further on this.  We can keep it in main repo as long as we can maintain/upgrade it without much of effort, which seems to be the case for now.

**Comment by lalitb** [comment]
> doc generation is failing, looking into this.

fixed now.

**Review by TommyCpp — APPROVED** [review]

**Pull request merged**
