### PR TITLE
Add base64 conversion traits

### LINKED ISSUE #54: Add a Base64 decoder
Often span IDs between applications are encoded into base64, currently you need to use an external crate i.e. https://crates.io/crates/base64 it would be more user friendly

### PR DESCRIPTION
**Pull request by xd009642**
I'll add some tests and more doc comments later just wanted to make sure this was in the ballpark of what was expected. 

Fixes #54

### CODE REVIEW

**Comment by jtescher** [comment]
@xd009642 yeah this direction looks good, maybe have this be an optional feature like serde is currently? Nice to keep the dependency list short for people who don't need all the features.

**Comment by xd009642** [comment]
I can do that once I finish work today :+1: base64 is a small dependency though with no subdependencies so should I at least make it a default feature?

**Comment by xd009642** [comment]
also I signed the cla/linuxfoundation so I guess that will switch to pass on the next commit I push?

**Comment by jtescher** [comment]
Sounds good! Normally I think default feature could make sense, however the binary format is in flux / may be removed so probably best to have this be opt-in for now.

**Comment by xd009642** [comment]
@jtescher I've moved base64 to it's own feature and also decided to do a blanket implementation for anything that implements `BinaryFormat` filled in the `to_base64` test replicating the binary format `to_bytes` test. Just need to fill in some more tests for the `from_base64`

**Comment by xd009642** [comment]
I signed it

**Comment by xd009642** [comment]
I signed it

**Comment by xd009642** [comment]
Done :smile:

**Pull request merged**
