### PR TITLE
sdk: Update sampling documentation

### PR DESCRIPTION
**Pull request by hdost**
* Move Sampling header into `Sampler`
* Enrich classes to have links in tracing module

Relates #800

Signed-off-by: Harold Dost <github@hdost.com>

### CODE REVIEW

**Comment by hdost** [comment]
@TommyCpp barring the obvious failures is this a good direction for #800?

**Comment by TommyCpp** [comment]
> @TommyCpp barring the obvious failures is this a good direction for #800?

Yeah I think it's a good start on docs, Thanks! I think we should sample at every span to be consistent with other SDKs. 

This has a risk of breaking change as the current behavior will be `Parent<SubSampler>` but I think it's worth it.

**Comment by jtescher** [comment]
Yeah we should follow the spec's steps here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sdk-span-creation

**Review by TommyCpp — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
