### PR TITLE
otlp: spawn thread to create blocking reqwest client

### LINKED ISSUE #2400: OTLP Exporter - initialize Reqwest::Blocking client must be done in non async context
Related to https://github.com/open-telemetry/opentelemetry-rust/issues/1757
Currently, initializing OTLP Exporter causes the creation of Reqwest::blocking client creation. If the user's main thread is a tokio::main or other asyn runtime context, this panics.

Reqwest::blocking client must be created separately to avoid this panic. Options include spinning up a throwaway thread, just for the sake of initializing the blocking client, or delaying the creation of client until 1st export.

Required for https://github.com/open-telemetry/opentelemetry-rust/issues/2386

### PR DESCRIPTION
**Pull request by pitoniak32**
fixes #2400

## Changes
Using a new thread to create reqwest blocking client to avoid panics from async main

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by pitoniak32** [comment]
I still need to test this, just getting this up to make sure its not off track.

**Comment by lalitb** [comment]
> 
> I still need to test this, just getting this up to make sure its not off track.

Thanks @pitoniak32. You can uncomment the integration test for [reqwest-blocking](https://github.com/open-telemetry/opentelemetry-rust/blob/main/scripts/integration_tests.sh#L13) to verify if it functions correctly with these changes? This mayn't necessarily work as there could be some issue with the integration test, I can check that separately in that case.

**Comment by cijothomas** [comment]
@pitoniak32 @lalitb 
I can confirm this is working as expected. https://github.com/open-telemetry/opentelemetry-rust/compare/main...cijothomas:cijothomas/testreq-block?expand=1 is the change I tried. Obviously, had to turn off logs/traces as they are using tokio, and won't work. But once that is also addressed, this should achieve what we want - which is to use background Thread + req::Blocking by default

**Comment by lalitb** [comment]
> @pitoniak32 @lalitb I can confirm this is working as expected. https://github.com/open-telemetry/opentelemetry-rust/compare/main...cijothomas:cijothomas/testreq-block?expand=1 is the change I tried. Obviously, had to turn off logs/traces as they are using tokio, and won't work. But once that is also addressed, this should achieve what we want - which is to use background Thread + req::Blocking by default

thanks @cijothomas. That makes me realize that the integration tests logs and traces for `reqwest-blocking` won't work till we run batch exporter as separate dedicated thread. @pitoniak32 - please ignore my earlier comment on enabling and validating integration test :)

**Comment by lalitb** [comment]
I can confirm these changes also work for batch log exporter modeled as separate thread in #2436.

**Review by lalitb — APPROVED** [review]

**Pull request merged**
