### PR TITLE
Exclude stdout exporter from codecoverage

### PR DESCRIPTION
**Pull request by cijothomas**

### CODE REVIEW

**Comment by lalitb** [comment]
Why are we excluding it ? It's part of the specs, and should be well tested, irrespective of whether it's used for debugging for production.

**Comment by cijothomas** [comment]
> Why are we excluding it ? It's part of the specs, and should be well tested, irrespective of whether it's used for debugging for production.

It should be well test, but manually? Are you suggesting we should setup tests by reading from stdout?
(Don't think its worth it)

**Comment by lalitb** [comment]
> Are you suggesting we should setup tests by reading from stdout?

No, I thought we should have unit-tests for specific components e.g., [transform](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-stdout/src/logs/transform.rs), and probably some mock test for stdout. This can't be a priority yet, as there are other things to stabilize, but good to visit sometime. Should we fine to remove for now, if we all agree.

**Comment by cijothomas** [comment]
> > Are you suggesting we should setup tests by reading from stdout?
> 
> No, I thought we should have unit-tests for specific components e.g., [transform](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-stdout/src/logs/transform.rs), and probably some mock test for stdout. This can't be a priority yet, as there are other things to stabilize, but good to visit sometime. Should we fine to remove for now, if we all agree.

Agree. Just reminded that we did have bugs like https://github.com/open-telemetry/opentelemetry-rust/pull/1747 before!

**Pull request closed without merging**
