### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by oriontvv**
This PR adds dependabot config

### CODE REVIEW

**Review by hdost — APPROVED** [review]
Looks good just need you to sign the CLA

**Comment by cijothomas** [comment]
@oriontvv Could you sign the CLA please? This is a hard requirement before we can accept any contributions.

**Comment by oriontvv** [comment]
@hdost  @cijothomas  done. there was an issue with signing in, already resolved.

**Comment by cijothomas** [comment]
Thanks @oriontvv ! Happy to see more contributions, if you have time and passion!

**Pull request merged**
