### PR TITLE
fix: otel-otlp will try to create another tokio runtime inside one if async feature was not enabled.

### PR DESCRIPTION
**Pull request by TommyCpp**
- The bug was introduced in #467. I believe the async feature was there to spin up a tokio runtime if the exporter was not already in one. It's mostly because the tonic cannot work without a tokio runtime.
- Renamed the async feature to be less confusing.
- Cleaned up all the clippy problems in the metrics module and add some links into the doc.
- Add a with_timeout method in `opentelemetry/sdk/metrics/controller/push.rs` push controller to config the timeout of each push.

### CODE REVIEW

**Comment by frigus02** [comment]
Looks good to me.

I have to admit, the feature name "tokio-sync" is still not super obvious to me. But I can't think of a better name, either. Should we explain this particular feature in the readme?

**Comment by djc** [comment]
This also seems to be fixing up quite a few formatting issues. We have rustfmt set up in CI, right? Shouldn't it be catching those.

I also find the `tokio-sync` name confusing. What are the semantics exactly? Maybe we can brainstorm a better name?

**Comment by TommyCpp** [comment]
> We have rustfmt set up in CI, right? Shouldn't it be catching those.

I believe rustfmt doesn't really format the document so that could be the reason. 

I think the feature whose name in question is `tonic-sync`, which helps the user to run a tonic client when the application itself is not in a tokio environment by creating a tokio runtime internally.

**Comment by djc** [comment]
I feel like we maybe just shouldn't provide that option. IIRC the error you get when spawning without a running runtime is pretty decent these days, and I feel like the cost/benefit ratio of providing this feature isn't so great.

**Comment by TommyCpp** [comment]
Yeah, that's a fair point. I would think most of the users will use tonic inside a tokio runtime.

**Review by frigus02 — APPROVED** [review]

**Review by djc — APPROVED** [review]

**Pull request merged**
