### PR TITLE
fix: revert modifications to Apache license

### PR DESCRIPTION
**Pull request by svrnm**
## Changes

See https://github.com/open-telemetry/community/issues/2056 for background

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [N/A] Unit tests added/updated (if applicable)
* [N/A] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [N/A] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Review by hdost — CHANGES_REQUESTED** [review]
Edit: its a couple links deep

**Review by hdost — APPROVED** [review]

**Review by lalitb — COMMENTED** [review]
LGTM. Thanks. @svrnm  Do you also plan to raise a similar fix for [opentelemetry-rust-contrib](https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main) repo?

**Review by lalitb — APPROVED** [review]

**Review by TommyCpp — APPROVED** [review]

**Comment by svrnm** [comment]
> LGTM. Thanks. @svrnm Do you also plan to raise a similar fix for [opentelemetry-rust-contrib](https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main) repo?

Oh yes, had it on my list, let me do that real quick!

**Comment by svrnm** [comment]
See https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/60

**Pull request merged**
