### PR TITLE
Use ureq for collector instead of reqwest blocking client

### PR DESCRIPTION
**Pull request by glademiller**

### CODE REVIEW

**Comment by jtescher** [comment]
great start! looks like there a a few lint issues and signing the CLA left

**Comment by glademiller** [comment]
I don't know that I have the bandwidth right now to get this all the way
across the line so would love if someone would take this and run with it.
If not I'm sure at some indeterminate moment in the future I could try to
get it across the line.

**Comment by LukeMathWalker** [comment]
I can pick this up :+1:

**Comment by glademiller** [comment]
@LukeMathWalker thanks for running with this I'll close this PR

**Pull request closed without merging**
