### PR TITLE
Update tonic -> 0.8.0

### PR DESCRIPTION
**Pull request by diceride**
https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#v080-2022-07-29

### CODE REVIEW

**Comment by diceride** [comment]
Please consider this for v0.18.0 release (https://github.com/open-telemetry/opentelemetry-rust/pull/779).

**Comment by djc** [comment]
Thanks for working on this! Changes look good so far, though I guess there's some more work to do before CI passes.

**Comment by diceride** [comment]
Some CI tests are flaky.

**Comment by djc** [comment]
Feel free to ignore the coverage test, and it looks like we have to bump the MSRV again. Feel free to ignore those!

**Review by djc — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
