### PR TITLE
Minor format update to maintainer and approver list

### PR DESCRIPTION
**Pull request by cijothomas**

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Review by hdost — APPROVED** [review]

**Comment by cijothomas** [comment]
The CI/lint is failing for a file untouched by this PR.. !

**Comment by djc** [comment]
Yeah, just clippy lints from the latest Rust release.

**Comment by cijothomas** [comment]
> Yeah, just clippy lints from the latest Rust release.

What action do you suggest me to follow? Do you expect me to fix that file? Or you can merge without it? Or you can make a separate to Fix the lint failure, and merge it first..

**Comment by djc** [comment]
We can merge without, and someone might be along to fix it in a separate PR.

**Pull request merged**
