### PR TITLE
rename duplicate examples

### PR DESCRIPTION
**Pull request by demoray**
When testing the at the workspace level, there are warnings about duplicate examples which may become a hard error from rust.  This PR renames the examples.

```
❯ cargo test --release
warning: output filename collision.
The example target `basic` in package `opentelemetry-stdout v0.3.0 (/REDACTED/opentelemetry-rust/opentelemetry-stdout)` has the same output filename as the example target `basic` in package
`opentelemetry-appender-tracing v0.3.0 (/HOME/opentelemetry-rust/opentelemetry-appender-tracing)`.
Colliding filename is: /REDACTED/opentelemetry-rust/target/release/examples/basic
The targets should have unique names.  Consider changing their names to be unique or compiling them separately.  This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `basic` in package `opentelemetry-stdout v0.3.0 (/REDACTED/opentelemetry-rust/opentelemetry-stdout)` has the same output filename as the example target `basic` in package `opentelemetry-appender-tracing v0.3.0 (/REDACTED/opentelemetry-rust/opentelemetry-appender-tracing)`.
Colliding filename is: /REDACTED/opentelemetry-rust/target/release/examples/basic
The targets should have unique names.  Consider changing their names to be unique or compiling them separately.  This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

Fixes #
Design discussion issue (if applicable) #

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by lalitb** [comment]
Should we also update the comment in these examples :
 - https://github.com/open-telemetry/opentelemetry-rust/blob/936c46639aa1521bf49dbffba49bbd9795f8ea58/opentelemetry-appender-tracing/examples/basic.rs#L1
 - https://github.com/open-telemetry/opentelemetry-rust/blob/936c46639aa1521bf49dbffba49bbd9795f8ea58/opentelemetry-stdout/examples/basic.rs#L1

Also, you have to sign the CLA for CI to succeed, and enable merging.

**Comment by demoray** [comment]
> Should we also update the comment in these examples :

Done

> Also, you have to sign the CLA for CI to succeed, and enable merging.

I've submitted a request to our CLA manager through the EasyCLA system.

**Review by lalitb — APPROVED** [review]
LGTM once CLA is signed.

**Review by cijothomas — APPROVED** [review]

**Review by TommyCpp — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
> > Should we also update the comment in these examples :
> 
> Done
> 
> > Also, you have to sign the CLA for CI to succeed, and enable merging.
> 
> I've submitted a request to our CLA manager through the EasyCLA system.

@demoray any luck with the CLA signing?

**Comment by cijothomas** [comment]
Closing old, inactive PRs. Feel free to reopen when CLA is signed or make a new PR. Thanks.

**Pull request closed without merging**
