### PR TITLE
Make all errors Box<dyn Error + Send + Sync + 'static>

### LINKED ISSUE #282: APis return Box<dyn Error> which isn't compatibile with useful ecosystem crates
A number of APIs, especially the `new_pipeline().install()` flavors return `Box<dyn Error>`. This trait bound is incompatible with useful ecosystem crates like `anyhow`, whose `Context` trait requires `Box<dyn Error + Send + Sync + 'static>`.

I'm happy to submit a PR to fix this. Are there any APIs where we _don't_ want this trait bound?

### PR DESCRIPTION
**Pull request by cpcloud**
This PR changes all errors to return `Box<dyn Error + Send + Sync + 'static>`
to be compatible with ecosystem crates and more generally to allow
errors to be moved to and shared across threads.

Closes #282.

### CODE REVIEW

**Comment by frigus02** [comment]
Looks like the examples need updating as well. Could you also update the example in the main README.md?

**Comment by cpcloud** [comment]
On it.

**Review by TommyCpp — COMMENTED** [review]
I think the only README left are in `opentelemetry-jaeger` and `opentelemetry-otel`.

**Review by frigus02 — APPROVED** [review]

**Comment by jtescher** [comment]
Thanks @cpcloud, this seems like an improvement as we work toward https://github.com/open-telemetry/opentelemetry-rust/issues/286

**Pull request merged**
