### PR TITLE
Release otel dynatrace 0.4.0

### PR DESCRIPTION
**Pull request by hdost**
More a notice so we can remove in the future
Relates #1099 

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by hdost** [comment]
@TommyCpp would you be able to release the exporter? Then I'll move forward with the removal for #1099

**Comment by hdost** [comment]
Maybe @jtescher ?

**Comment by jtescher** [comment]
Yep I can release it

**Comment by jtescher** [comment]
Released https://crates.io/crates/opentelemetry-dynatrace/0.4.0

**Comment by hdost** [comment]
Thank you !

**Pull request merged**
