### PR TITLE
Ignore flaky opentelemetry-jaeger tests

### LINKED ISSUE #1505: Flaky test in CI
failures:

---- exporter::config::collector::http_client::collector_client_tests::test_bring_your_own_client stdout ----
Error: ExportFailed(ConfigError { pipeline_name: "collector", config_name: "collector_endpoint", reason: "invalid uri from environment variable, invalid uri character" })

---- exporter::config::collector::tests::test_collector_exporter stdout ----
thread 'exporter::config::collector::tests::test_collector_exporter' panicked at opentelemetry-jaeger/src/exporter/config/collector/mod.rs:580:9:
assertion failed: exporter.is_ok()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    exporter::config::collector::http_client::collector_client_tests::test_bring_your_own_client
    exporter::config::collector::tests::test_collector_exporter

test result: FAILED. 9 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

error: test failed, to rerun pass `-p opentelemetry-jaeger --lib`
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test --tests --manifest-path /home/runner/work/opentelemetry-rust/opentelemetry-rust/Cargo.toml --target-dir /home/runner/work/opentelemetry-rust/opentelemetry-rust/target/llvm-cov-target --locked --all-features --workspace` (exit status: 101)

### PR DESCRIPTION
**Pull request by mattbodd**
Fixes #1505
Two tests have been intermittently failing from the `opentelemetry-jaeger` crate:
    exporter::config::collector::http_client::collector_client_tests::test_bring_your_own_client
    exporter::config::collector::tests::test_collector_exporter

As the `opentelemetry-jaeger` crate will be removed in the next major release, these tests can be ignored for the time being to alleviate the issue.

## Changes

Ignores tests:
exporter::config::collector::http_client::collector_client_tests::test_bring_your_own_client
exporter::config::collector::tests::test_collector_exporter

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by cijothomas** [comment]
> I think this works.
> 
> The issue here is we didn't isolate the env vars between tests. A more robust fix probably is running jaeger tests in single thread.
> 
> Maybe we can ignore the jaeger in coverage tests?

yes. I think the easiest approach is to just ignore the tests, and do the jaeger release, followed by its code+tests removal.

**Comment by mattbodd** [comment]
Thanks @TommyCpp and @cijothomas for your comments. As Cijo mentioned, since we are deprecating opentelemetry-jaeger I didn't opt to fix these flaky tests and instead just silenced them so CI doesn't fail. Is there anything I should do differently or can this change be merged?

**Review by cijothomas — APPROVED** [review]

**Review by TommyCpp — APPROVED** [review]
Let add a comment that says we ignore this because it's flaky and won't fix because jaeger has been deprecated

**Comment by mattbodd** [comment]
> Let add a comment that says we ignore this because it's flaky and won't fix because jaeger has been deprecated

This is a good suggestion. I've left a comment above each ignored test.

**Pull request merged**
