### PR TITLE
chore: convert to intra-doc links

### PR DESCRIPTION
**Pull request by Folyd**
This PR converts all legacy-style doc links to intra-doc links.

### CODE REVIEW

**Review by djc — APPROVED** [review]
This looks great, thanks!

The only thing I was thinking about is that I don't love the `super::super` (although clearly that's kind of how it was before). How do you feel about replacing those with `crate::`-rooted paths?

**Comment by Folyd** [comment]
> This looks great, thanks!
> 
> The only thing I was thinking about is that I don't love the `super::super` (although clearly that's kind of how it was before). How do you feel about replacing those with `crate::`-rooted paths?

Thanks for reviewing. This has been fixed with the new patch. 🍺

**Comment by djc** [comment]
Nice, thanks!

**Review by TommyCpp — COMMENTED** [review]
> ```
> $ cargo doc --no-deps     
> warning: unresolved link to `GlobalProvider`
>   --> opentelemetry/src/global/trace.rs:68:16
>    |
> 68 | /// Wraps the [`GlobalProvider`]'s [`Tracer`] so it can be used generically by
>    |                ^^^^^^^^^^^^^^^^ no item named `GlobalProvider` in scope
>    |
>    = note: `#[warn(broken_intra_doc_links)]` on by default
>    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
> ```

Thanks for the great work! I think this should be `crate::global::GlobalTracerProvider`. We rename it from `GlobalProvider` a while ago but didn't seem to update the doc.

**Comment by Folyd** [comment]
> I think this should be crate::global::GlobalTracerProvider. We rename it from GlobalProvider a while ago but didn't seem to update the doc.

@TommyCpp This has been resolved. Thanks a lot.

**Pull request merged**
