### PR TITLE
Add Utkarsh as maintainer

### PR DESCRIPTION
**Pull request by cijothomas**
Utkarsh has been playing a key role in advancing this project as an approver for last few months. He started with Metrics signal, but has since then expanded to cover entire repo.
His thorough reviews and guidance are well appreciated by contributors.

Proposing to make Utkarsh a maintainer for this project.

### CODE REVIEW

**Review by lalitb — APPROVED** [review]

**Comment by utpilla** [comment]
Thank you! I look forward to helping maintain this repo.

**Comment by TommyCpp** [comment]
cc @jtescher @hdost

**Review by jtescher — APPROVED** [review]

**Comment by lalitb** [comment]
cc @hdost

**Review by utpilla — APPROVED** [review]

**Comment by cijothomas** [comment]
All criterion from https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#becoming-a-maintainer is satisfied, merging.

The person being nominated has accepted the nomination by approving the pull request - Done
All maintainers have approved the pull request OR a majority of maintainers have approved the pull request and no maintainer has objected by requesting changes on the pull request. In the case that all maintainers have not given approval, the pull request should stay open for a minimum of 5 days before merging.

**Nominated person has accepted, Majority maintainers approved, no objections from others, and 5 days has elapsed.**

**Comment by cijothomas** [comment]
Welcome @utpilla to @open-telemetry/rust-maintainers !

**Pull request merged**
