### PR TITLE
Prepare for v0.20.0 release

### PR DESCRIPTION
**Pull request by jtescher**
See the individual changelogs for details

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
I suppose #1164 should block the release?

**Comment by hdost** [comment]
> I suppose #1164 should block the release?

Seems closed now, but this might need to be rebased.

**Comment by cijothomas** [comment]
@open-telemetry/rust-approvers Could you proceed with this release at your earliest? Its been a while since there was a new release.

**Review by TommyCpp — APPROVED** [review]
👍 LGTM. I don't see any pending changes that must should block this release

**Pull request merged**
