### PR TITLE
Fix serde

### PR DESCRIPTION
**Pull request by hwrdtm**
Make compatible with Collector serde shape

## Changes

This PR:
- Flattens some `data` and `value` fields in order to be consistent with the JSON schema implemented on the OTEL Collector
  - See [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/internal/data/protogen/metrics/v1/metrics.pb.go#L469) for the struct defs and JSON tags
  - Also see [here](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.3.1/examples/metrics.json) for an example resource metric in JSON
- Make the `common::v1::KeyValue::value` field serde into an `Option<AnyValue>` rather than the direct serialized value in order to be consistent with the JSON schema implemented on the OTEL Collector
  - See [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/internal/data/protogen/common/v1/common.pb.go#L288) for the struct defs and JSON tags
  - Also see [here](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.3.1/examples/trace.json#L40-L42) for an example resource span in JSON
  - Similar comment made on an earlier PR: https://github.com/open-telemetry/opentelemetry-rust/pull/1462/files#r1623330058

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by TommyCpp** [comment]
Sorry I saw you comment on my previous PR but didn't get a chance to dig deep and reply 😞 Will take another look today

**Comment by lalitb** [comment]
@hwrdtm - These proto-generated rust files shouldn't be directly modified. The files are generated using [grpc_build.rs](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/tests/grpc_build.rs), and most probably you need to modify this build script for the required changes in the proto files.

**Comment by hwrdtm** [comment]
> @hwrdtm - These proto-generated rust files shouldn't be directly modified. The files are generated using [grpc_build.rs](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/tests/grpc_build.rs), and most probably you need to modify this build script to get the required changes in the proto files.

done, and CI passing now.

**Comment by lalitb** [comment]
@hwrdtm  Had a quick look into the PR. I am not sure what's wrong with the `serialize_to_value` conversion, as it generates the correct JSON format as [here](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/tests/integration_test/expected/traces.json#L31C1-L33C20). Or are you specifically fixing the `flattening` in case of nested attributes?

**Comment by hwrdtm** [comment]
> @hwrdtm Had a quick look into the PR. I am not sure what's wrong with the `serialize_to_value` conversion, as it generates the correct JSON format as [here](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/tests/integration_test/expected/traces.json#L31C1-L33C20). Or are you specifically fixing the `flattening` in case of nested attributes?

@lalitb not sure how the deserialization is working as in [this test](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/tests/integration_test/tests/traces.rs#L77), but the serialization path is definitely not producing the same result - I implemented a serde test in [another PR to demonstrate, check it out for more details](https://github.com/open-telemetry/opentelemetry-rust/pull/1860).

Also my comment [here](https://github.com/open-telemetry/opentelemetry-rust/pull/1462/files#r1623330058) has an example for what the issue is. Basically, we are currently getting this during serialization:

```
"value": "100"
```

when we want

```
"value": {
  "intValue": 100
}
```

**Comment by TommyCpp** [comment]
Not sure if 

```
"value": {
  "intValue": 100
}
```

is the expected result as pointed out in https://github.com/open-telemetry/opentelemetry-rust/pull/1753, [int64, fixed64, uint64 should be serialized as string in json](https://protobuf.dev/programming-guides/proto3/#json).

I think we should fix the `serialize_to_value` function

**Comment by hwrdtm** [comment]
> Not sure if
> 
> ```
> "value": {
>   "intValue": 100
> }
> ```
> 
> is the expected result as pointed out in #1753, [int64, fixed64, uint64 should be serialized as string in json](https://protobuf.dev/programming-guides/proto3/#json).
> 
> I think we should fix the `serialize_to_value` function.
> 
> I think we want
> 
> ```
> "value": {
>   "intValue": "100"
> }
> ```

@TommyCpp From the [proto docs](https://protobuf.dev/programming-guides/proto3/#json)

>JSON value will be a decimal string. Either numbers or strings are accepted.

So I think either works.

Actually I verified this locally and my OTEL Collector parsed the `"intValue": 100` just fine. 

Also [this example trace in the open-telemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/ptrace/json_test.go#L91) uses a mixture of strings for the `intValue` and numbers for the `doubleValue`.

Also quick repo search in each of the `open-telemetry/opentelemetry-rust` and `open-telemetry/opentelemetry-collector` shows that there is a mixture of string and number values used for `intValue`:
- [open-telemetry/opentelemetry-rust](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-rust%20%22%5C%22intValue%5C%22%22&type=code)
- [open-telemetry/opentelemetry-collector](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector+%22%5C%22intValue%5C%22%22&type=code)

However, if you feel strongly towards making consistent use of numbers, happy to do that too.

**Comment by lalitb** [comment]
> So I think either works.

> Actually I verified this locally and my OTEL Collector parsed the "intValue": 100 just fine.

Yes, either will work. However, not all JSON parsers may not support the full range of 64-bit integers, so serializing as strings ensures compatibility. Although, during deserialization, we should be able to handle both string and int.

**Comment by lalitb** [comment]
@hwrdtm - I validate your test in PR #1860 with fix in `serialize_to_json` here - https://github.com/open-telemetry/opentelemetry-rust/compare/main...lalitb:test-serde-int64?expand=1

This will ensure that we serialize as
```json
"value": {
  "intValue": "100"
}
```

and not
```json
"value": {
  "intValue": 100
}
```
or 
```json
"value": "100"
```

I didn't test it fully, but if you think we can use those changes in this PR :)

**Review by lalitb — CHANGES_REQUESTED** [review]
as discussed here - https://github.com/open-telemetry/opentelemetry-rust/pull/1856#issuecomment-2149082284

**Comment by lalitb** [comment]
@hwrdtm Do you need any help in incorporating the changes as discussed above, including the unit test from #1860? If it helps, I can create a separate PR for it. #1835 is also blocked on this, so checking.

**Comment by hwrdtm** [comment]
@lalitb last time I tried looking down the path of changing the logic in the serializers I was having some trouble. I don't think I'll have time to get back to this PR until mid next week - feel free to help get it over the finish line.

**Comment by lalitb** [comment]
fix incorporated in #1882.

**Comment by hwrdtm** [comment]
hey @lalitb , thanks for merging in #1882 .

I don't think the other fixes in this PR [as referred to here](https://github.com/open-telemetry/opentelemetry-rust/pull/1856/files#diff-de65d8dec0d45df73e6ffc6f0022e3c395b260debd5c76120713c9cb102f87f5R103-R105) got incorporated though? I am referring to the fixes for these fields:

```
        "metrics.v1.Metric.data",
        "metrics.v1.NumberDataPoint.value",
        "metrics.v1.Exemplar.value",
```

**Comment by lalitb** [comment]
> hey @lalitb , thanks for merging in #1882 .
> 
> I don't think the other fixes in this PR [as referred to here](https://github.com/open-telemetry/opentelemetry-rust/pull/1856/files#diff-de65d8dec0d45df73e6ffc6f0022e3c395b260debd5c76120713c9cb102f87f5R103-R105) got incorporated though? I am referring to the fixes for these fields:
> 
> ```
>         "metrics.v1.Metric.data",
>         "metrics.v1.NumberDataPoint.value",
>         "metrics.v1.Exemplar.value",
> ```

@hwrdtm I haven't tested, but do we need them. I believe all these fields use "common::v1::KeyValue" internally, and we already have custom serialization for [it](https://github.com/open-telemetry/opentelemetry-rust/blob/e0fb7fe3b7ab343cdf2f702b04d04976dc5542ca/opentelemetry-proto/tests/grpc_build.rs#L97). If you foresee any issue, feel free to raise an PR, else I can validate it out later next week.

**Pull request closed without merging**
