### PR TITLE
release(v0.19): add initial change log

### PR DESCRIPTION
**Pull request by TommyCpp**
We are still blocked by some memory issue investigation but once it resolved we should be able to cut a release

### CODE REVIEW

**Comment by djc** [comment]
I think we should deal with #969 before releasing.

Is it intentional that the integration tests job is getting skipped in CI? Should we run it manually before release?

**Comment by TommyCpp** [comment]
> Is it intentional that the integration tests job is getting skipped in CI?

Yeah I intend to expand the integration test coverage so I expect the time to run it grows over time. And it may not needed to run for every commit/PR. But we should run it before release.

**Comment by TommyCpp** [comment]
Listed the following issues as blocking before 0.19 release, feel free to add more:

- [ ] #901 Need review

**Comment by hdost** [comment]
@TommyCpp Is the blocker still the memory issue?

**Comment by TommyCpp** [comment]
> @TommyCpp Is the blocker still the memory issue?

No the memory issue is false alarm for this repo(the issue is not in our crate) so we are good on that front. I can update the changelog but we probably still need #901 to sign LCA?

**Comment by hdost** [comment]
Should we place a time limit on the #901 change, if it's not merged by X date then we merge and release?

**Comment by TommyCpp** [comment]
> Should we place a time limit on the #901 change, if it's not merged by X date then we merge and release? 

Plan to cut release this weekend. We can do a minor release for #901 if needed

**Comment by TommyCpp** [comment]
I think that's all changes we want to land in v0.19. PTAL cc @open-telemetry/rust-approvers

**Review by jtescher — APPROVED** [review]

**Comment by jtescher** [comment]
@TommyCpp should we release version 0.20.0 as a follow up once #1000 lands?

**Comment by TommyCpp** [comment]
> @TommyCpp should we release version 0.20.0 as a follow up once #1000 lands?

Yep I think #1000 contains lots of change and maybe released as follow up.

I will wait until tomorrow to gather more thoughts for this release. But if there is not I will merge it.

**Review by hdost — APPROVED** [review]

**Comment by glynnmccabe** [comment]
@TommyCpp the datadog export is broken for version 05. I made a small fix here: https://github.com/open-telemetry/opentelemetry-rust/pull/1002

Tested locally and working as expected.

Would be nice to get this in the release if possible :)

**Comment by hdost** [comment]
🚀  thank you @TommyCpp

**Pull request merged**
