### PR TITLE
limit futures deps

### PR DESCRIPTION
**Pull request by asonix**
This change removes the dependency on futures-io by depending directly on futures-core in opentelemetry-otlp and futures-util, futures-channel, and futures-executor in opentelemetry

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
If you can't tell if it did anything, it probably didn't. It should open a web page and lead you through installing a GitHub app and agreeing to the CLA. Did that not happen for you?

**Comment by asonix** [comment]
@djc it connected the bot to my github account but didn't walk me through signing a CLA. it could be one of my many firefox extensions breaking it, so I'll try again after disabling some of those

**Review by TommyCpp — APPROVED** [review]
Looks good. Thanks!

**Comment by asonix** [comment]
looks like opentelemetry-otlp cannot be changed this way, since futures is referenced directly in generated code due to this line in grpcio-compiler: https://github.com/tikv/grpc-rs/blob/master/compiler/src/codegen.rs#L595

It's a shame, since Future is even in the standard library now

**Pull request closed without merging**
