### PR TITLE
Fix broken docs

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Comment by djc** [comment]
Maybe add a CI step along these lines? Should help catch these issues in CI.

```
    - name: doc
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: -Dwarnings
```

**Comment by djc** [comment]
Why not fix up those allow thingies?

**Comment by jtescher** [comment]
They are in generated code, taking a look.

**Comment by djc** [comment]
That's fair. Would be nice if we can restrict the allows to the generated code and/or add a comment that they're there because of generated code.

**Review by djc — APPROVED** [review]

**Comment by jtescher** [comment]
That should take care of the semantic convention crate, the stackdriver issues will take some more work. Can do those in a follow up.

**Pull request merged**
