### PR TITLE
Requesting Maintainership for h.dost

### PR DESCRIPTION
**Pull request by hdost**
As per the [guidelines](https://github.com/open-telemetry/community/blob/main/community-membership.md#becoming-a-maintainer) for the OpenTelemetry project. I am requesting maintainership.

> Unless stated otherwise in a SIG charter ratified by the Technical Committee, a new maintainer is elected by vote of the existing maintainers of the SIG. The vote is officially started when a pull request to add a new maintainer is opened, and ends when the pull request is merged. The pull request may be merged when the following conditions are met:
>
>    - The person being nominated has accepted the nomination by approving the pull request
>    - All maintainers have approved the pull request OR a majority of maintainers have approved the pull request and no maintainer has objected by requesting changes on the pull request. In the case that all maintainers have not given approval, the pull request should stay open for a minimum of 5 days before merging.
>
> The nominee is considered a maintainer after the pull request is merged.

### CODE REVIEW

**Review by shaun-cox — APPROVED** [review]

**Comment by hdost** [comment]
@djc, @jtescher, @TommyCpp Do you have any objections? I'd prefer if all of you have time to object.

**Review by cijothomas — APPROVED** [review]
I support!

**Comment by jtescher** [comment]
I support as well, @cijothomas want to request as well?

**Review by TommyCpp — APPROVED** [review]
I support! +1 if @cijothomas wants to join the maintainers

**Review by lalitb — APPROVED** [review]

**Comment by lalitb** [comment]
+1 for @cijothomas and @hdost

**Comment by jtescher** [comment]
Merging as this appears to have broad support 👍

**Pull request merged**
