### PR TITLE
export EvictedQueue::new

### PR DESCRIPTION
**Pull request by inanna-malick**
Allow for the construction of `EvictedQueue`, as with `EvictedHashMap`. This would allow users of your library to construct `SpanData` instances directly - every other field of that struct can be initialized using public constructors.

Thanks for making this open source, btw!

### CODE REVIEW

**Comment by jtescher** [comment]
This seems reasonable, just need to sign the cla 👍

**Comment by inanna-malick** [comment]
I've signed the individual contributor agreement.

**Comment by jtescher** [comment]
Great thanks!

**Comment by inanna-malick** [comment]
Thanks! Do you think there's any chance you'd be able to get this out in a minor release?

**Comment by jtescher** [comment]
Yes working on getting one out now 👍

**Pull request merged**
