### PR TITLE
Prepare for v0.15.0 release

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Review by TommyCpp — APPROVED** [review]
LGTM 🎉

**Review by TommyCpp — COMMENTED** [review]
One thing that we may want to change is the current OTLP metric exporter is broken in some cases because the collector hasn't updated to the latest version. 
> For the record, the proto submodule has to be checked out to commit 8ab21ed9a to have it working.

Maybe we should downgrade first to match the collector?

**Comment by jtescher** [comment]
@TommyCpp should we merge this now? could be nice to have a little more time to consider #571

**Comment by TommyCpp** [comment]
Yeah, I think we can merge it 👍 . I am still looking at options to lock the commit of submodule but don't think I can get it done tonight. And I also think we should give #571 more time to consider all possibilities,

**Pull request merged**
