### PR TITLE
[Metrics API] Mark NoopMeterProvider as pub(crate)

### PR DESCRIPTION
**Pull request by utpilla**
## Changes
- `NoopMeterProvider` is only used in the API project

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
changelog as this is removing existing public api though this should affect noone?

**Comment by lalitb** [comment]
Just confirm if this is specs compliant - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/noop.md, as per the specs - "All language implementations of OpenTelemetry MUST provide a No-Op."

**Comment by cijothomas** [comment]
> Just confirm if this is specs compliant - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/noop.md, as per the specs - "All language implementations of OpenTelemetry MUST provide a No-Op."

This is spec compliant. We have no-op behavior, just not exposing them to public.

**Comment by lalitb** [comment]
> This is spec compliant. We have no-op behavior, just not exposing them to public.

What if the user wants to explicitly set the no-op provider, to (say) disable the telemetry?  As per the specs, the noop is for end-user.

**Comment by cijothomas** [comment]
> > This is spec compliant. We have no-op behavior, just not exposing them to public.
> 
> What if the user wants to explicitly set the no-op provider, to (say) disable the telemetry? As per the specs, the noop is for end-user.

If there is a need for that, we can offer mechanisms to achieve that.
(Tracing spec does not have the equivalent part in the spec like Metrics)

**Comment by phillipleblanc** [comment]
Can we make this public again? I was depending on this to disable telemetry selectively. cc @cijothomas

**Comment by lalitb** [comment]
> Can we make this public again? I was depending on this to disable telemetry selectively. cc @cijothomas

@phillipleblanc Not directly answering comment, even though I voted above to keep the API. But just to say "Hi" - Not sure you remember, but we worked together in App Center (VSAC) in Microsoft :)

**Comment by phillipleblanc** [comment]
Hey, yep I remember! Small world :)

**Comment by lalitb** [comment]
> Can we make this public again? I was depending on this to disable telemetry selectively. cc @cijothomas

back to the query, if you would like to use NoopMeterProvider to disable telemetry, you can save the handle initially at startup, and use it later when required. To demonstrate this (refer the use of `wrapped_noop_provider`):
https://github.com/open-telemetry/opentelemetry-rust/compare/main...lalitb:use-noop-provider?expand=1

**Comment by phillipleblanc** [comment]
I ended up copying the implementation of `NoopMeterProvider` into my project, which is also what `tracing-opentelemetry` did: https://github.com/tokio-rs/tracing-opentelemetry/pull/184#issuecomment-2473551231

**Comment by cijothomas** [comment]
> Can we make this public again? I was depending on this to disable telemetry selectively. cc @cijothomas

Could you open a new issue for this, so we can track accordingly?

**Comment by phillipleblanc** [comment]
Filed! https://github.com/open-telemetry/opentelemetry-rust/issues/2444

**Pull request merged**
