### PR TITLE
Add basic example showing how to use various metric instruments

### PR DESCRIPTION
**Pull request by cijothomas**
Towards https://github.com/open-telemetry/opentelemetry-rust/issues/1060

## Changes

Adds a example which showcases the usage of various instruments. The stdout exporter is used to display metrics.
There'll be a separate PR which shows common customizations, like changing temporality, using views, changing interval etc.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by TommyCpp — APPROVED** [review]
Looks reaonable to me. I understand we have too many examples at this point but with the new metrics example I think this one will be really benificial for users. We can probably clean up some other examples to reduce maintaince burdan

**Comment by cijothomas** [comment]
> Looks reaonable to me. I understand we have too many examples at this point but with the new metrics example I think this one will be really benificial for users. We can probably clean up some other examples to reduce maintaince burdan

Agree. I'll be able to help with some cleanups/consolidation of the examples.

**Comment by cijothomas** [comment]
@TommyCpp Could you merge please?

**Comment by gautamg795** [comment]
Does your example of recording data to a histogram here use the `ExponentialBucketHistogram` type under the hood, or is it using an explicitly bucketed histogram with some default value for the buckets?

**Comment by cijothomas** [comment]
> Does your example of recording data to a histogram here use the `ExponentialBucketHistogram` type under the hood, or is it using an explicitly bucketed histogram with some default value for the buckets?

It follows the spec, which states that the default is ExplicitBucket aggregation, using the default buckets. 
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/reader.rs#L154

**Pull request merged**
