### PR TITLE
Add keys method to extractors

### LINKED ISSUE #195: Add `keys` method to extractors
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/825) for details.

### PR DESCRIPTION
**Pull request by siyopao**
First attempt at #195. I could probably use some help with the documentation though 🙇  

Closes #195.

### CODE REVIEW

**Comment by jtescher** [comment]
@siyopao great start! What do you think about having `keys` return an iterator over `&str`s instead of a `Vec`? Could help people avoid the additional allocation.

**Comment by siyopao** [comment]
Thanks for the comment @jtescher. Good idea! I've updated to return an iterator.

**Comment by jtescher** [comment]
@siyopao Sorry I hadn't looked into this closely enough, I don't think we can have this be an iterator without additional allocations as the lifetimes for something like `&dyn Iterator<Item=&str>` can't be easily resolved. @TommyCpp any clever ideas here? If not then the original `Vec<String>` is probably the better return type here.

**Comment by TommyCpp** [comment]
> @siyopao Sorry I hadn't looked into this closely enough, I don't think we can have this be an iterator without additional allocations as the lifetimes for something like `&dyn Iterator<Item=&str>` can't be easily resolved.

I agree. There is no guarantee how extractors will store those keys. So we may as well use `Vec`

**Comment by siyopao** [comment]
No worries. Reverted that commit.

**Review by jtescher — APPROVED** [review]
Ok looks good 👍

**Pull request merged**
