### PR TITLE
Prepare for v0.18.0 release

### PR DESCRIPTION
**Pull request by jtescher**
See [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-rust/blob/main/VERSIONING.md) for what is being stabilized.

### CODE REVIEW

**Comment by djc** [comment]
Hm, not sure if this is a good idea. The way Cargo version resolution, it considers pre-releases semver-compatible with other pre-releases for the same release. Thus, if you release this and there would later be a 1.0.0-beta.2 with any semver-incompatible changes in it, you would break all downstream users.

**Comment by jtescher** [comment]
@djc good point, is there a better beta convention?

**Comment by TommyCpp** [comment]
+1 on release using 0.x version and adding notes to communicate this is a beta 1.0 release. Also, I don't think the VERSIONING.md is clear about what we are stabilizing(should only be the `trace` feature). Maybe need to add that to the release note?

**Comment by TommyCpp** [comment]
Do we want to wait for #781 as it has an API change?

**Comment by djc** [comment]
> Do we want to wait for #781 as it has an API change?

I think that would make sense.

**Comment by jwilm** [comment]
Any chance this will land soon? We are eagerly awaiting the new version. :smile:

**Comment by jtescher** [comment]
Should be soon hopefully, just have to resolve the MSRV issues on main

**Comment by jtescher** [comment]
@open-telemetry/rust-approvers should we wait for the current open PRs to land? or merge this sooner than that.

**Comment by TommyCpp** [comment]
I think we should include #833 as it includes a fairly important fix for sampling IMO

**Review by djc — COMMENTED** [review]
LGTM, 🚢!

**Comment by jtescher** [comment]
@djc need a 👍 to merge 😄

**Review by TommyCpp — APPROVED** [review]
🛳️

**Pull request merged**
