### PR TITLE
Fix coverage tests

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Comment by TommyCpp** [comment]
I think there are still some issues with codecov. Maybe we need to update their default branch to `main`?

**Comment by jtescher** [comment]
Hm something odd with gcov

```
==> Running gcov in . (disable via -X gcov)
./target/debug/deps/serde_qs-449a08a5b9a9f17e.gcno:version '408*', prefer 'A93*'
find: ‘gcov’ terminated by signal 11
```

**Comment by TommyCpp** [comment]
> Hm something odd with gcov
> 
> ```
> ==> Running gcov in . (disable via -X gcov)
> ./target/debug/deps/serde_qs-449a08a5b9a9f17e.gcno:version '408*', prefer 'A93*'
> find: ‘gcov’ terminated by signal 11
> ```

It has been the error we see for a while. Checked the GitHub action repo but I didn't find anything obvious. I believe the report was uploaded to codecov according to the log. But the codecov cannot process it somehow.

**Comment by jtescher** [comment]
@TommyCpp specifying the output file seems to have fixed the issue 🎉

**Review by TommyCpp — APPROVED** [review]
Nice fix :tada:

**Pull request merged**
