### PR TITLE
Upgrade to tonic 0.11 and prost 0.12

### LINKED ISSUE #1458: [Feature]: update tonic dependency to 0.10.x
### Related Problems?

_No response_

### Describe the solution you'd like:

I'd like opentelemetry-rust to bump its tonic dependency to 0.10.x, so it's usable to use opentelemetry with a tonic 0.10.x project.

### Considered Alternatives

Re-exporting the tonic that's used in opentelemetry itself, and being able to wrap things on the client side - but that's a lot of work.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by djc**
Fixes #1458, replaces #1310 and #1461.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by djc** [comment]
This test failure in coverage seems unrelated:

```
---- metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called stdout ----
thread 'metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called' panicked at opentelemetry-sdk/src/metrics/mod.rs:674:13:
No scope metrics in latest export
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called

test result: FAILED. 115 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out; finished in 2.01s
```

**Review by hdost — APPROVED** [review]
Looks good thank you for the bump.

**Comment by alexheretic** [comment]
Thanks for bumping tonic! It would be great to get a new release using tonic `0.11`.

**Comment by hdost** [comment]
> Thanks for bumping tonic! It would be great to get a new release using tonic 0.11.

There's a pending release PR https://github.com/open-telemetry/opentelemetry-rust/pull/1539

**Pull request merged**
