### PR TITLE
Mark SdkMeter as pub(crate)

### PR DESCRIPTION
**Pull request by utpilla**
## Changes
- `SdkMeter` should not be `public`

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by TommyCpp — COMMENTED** [review]
This is a breaking change so maybe a change note?

**Comment by cijothomas** [comment]
> This is a breaking change so maybe a change note?

+1. We also need to add one for https://github.com/open-telemetry/opentelemetry-rust/pull/2085 too

**Comment by cijothomas** [comment]
Merging. Missing changelogs can be added in a follow up for both together.

**Comment by hdost** [comment]
Can i get a rational on this? Perhaps I am missing some context. Is it because users should use a builder and not the SdkMeter directly?

**Comment by cijothomas** [comment]
> Can i get a rational on this? Perhaps I am missing some context. Is it because users should use a builder and not the SdkMeter directly?

From the examples:

    let meter = global::meter("mylibraryname");
// OR
// let meter = meter_provider.meter("mylibraryname");

    // Create a Counter Instrument from above meter
    let counter = meter.u64_counter("my_counter").init();

SdkMeter not required to do this, and OTel's expectation is also rely on API only, not SDK constructs like SdkMeter, as that would tie their instrumentation to a specific SDK implementation (negating one of the original goals of OTel).

I also look at this from another angle - some pub thing was removed, and still all examples continue to compile, indicating that this should not have been public in the first place. Should work _most_ of the time to help clean up public APIs to the absolute minimum required.

**Pull request merged**
