### PR TITLE
Add ID methods for hex and byte array formatting

### LINKED ISSUE #194: Add methods to trace/span id to format as hex and byte array
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/836) for details.

### PR DESCRIPTION
**Pull request by awiede**
Fixes #194 

Add methods to SpanId and TraceId to format as lower Hex and big endian byte array.

### CODE REVIEW

**Comment by awiede** [comment]
Wondering if I should add methods to build a `TraceId` and a `SpanId` from hex/byte array? The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#retrieving-the-traceid-and-spanid) only specifies retrieval methods, but I think it could be useful to add `from_*` methods.

**Comment by jtescher** [comment]
@awiede I'm not against having from impls, do you have a use case in mind? seems like common usage may not be creating any ids generally

**Comment by awiede** [comment]
@jtescher I came across this because I just implemented an AWS X-Ray propagator which had to parse a hex trace ID. It's not a hug deal to delegate the hex --> decimal conversion to the propagator code, but I'd assume that wouldn't be specific to just that vendor.

**Comment by awiede** [comment]
@jtescher - Added here.

**Pull request merged**
