### PR TITLE
Fix config for otlp example and integration test

### LINKED ISSUE #1998: [Bug]: otlp example does not work without configuration update
### What happened?

I tried to run [basic-otlp example](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp/examples/basic-otlp) and it simply didn't work.

I update the first section of otel-collector-config.yml to the following
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
```
and it started working.

### API Version

0.24.0

### SDK Version

0.24.1

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell
OpenTelemetry log error occurred. Exporter otlp encountered the following errors: the grpc server returns error (The operation was cancelled): , detailed error message: operation was canceled
```

### PR DESCRIPTION
**Pull request by krlohnes**
Fixes #1998

## Changes

With updates to the otel collector 0.104+, the collector now binds to localhost by default. The config now needs to explicitly allow access from outside the docker container.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by lalitb** [comment]
@krlohnes Thanks for the PR. Changes look good, but you need to sign the CLA before it can be merged.

**Comment by krlohnes** [comment]
@lalitb I'm working through the CLA process with the company I work for.

**Comment by cijothomas** [comment]
@krlohnes Any progress with getting CLA process solved?

**Comment by krlohnes** [comment]
@cijothomas I unfortunately haven't made any progress on that front. I'm going to close this.

**Pull request closed without merging**
